version: '3.3'

services:
    db:
        image: mysql:5.7
        volumes:
            - ./mysql:/var/lib/mysql
        ports:
            - "4306:3306"
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: aerials5021
            MYSQL_DATABASE: wordpress
            MYSQL_USER: wordpress
            MYSQL_PASSWORD: wordpress.1

    wordpress:
        depends_on:
            - db
        image: wordpress:latest
        volumes:
            - ./src:/var/www/html
        ports:
            - "80:80"
        restart: always
        environment:
            WORDPRESS_DB_HOST: db
            WORDPRESS_DB_USER: wordpress
            WORDPRESS_DB_PASSWORD: wordpress.1
            WORDPRESS_DB_NAME: wordpress

volumes:
    mysql:
    src:
